version: "3.9"
services:
  xui:
    image: local/xui:latest
    ports:
      - "54321:54321"
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    tmpfs:
      - /home/pwuser/bin:uid=4001
    volumes:
      - ./db/:/etc/x-ui
      - ./cert/:/root/cert
